Weather App Javascript
gitnyasha/weather-app pull request #1
Opened 2020-06-06 15:05 UTC by gitnyasha

- weather information of each searched city
- toggle-button to change Fahrenheit and celsius

2020-06-08 04:07 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi @gitnyasha 👋 

You have done a good job thus far! 🙁 

Just one required feature missing. 😅 

#### Required changes
- you are missing the feature that changes a feature of the app base on type of weather city returns. See this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from Odin.
- Your temperature toggle also does not always work. When I search for some cities it does not toggle the temperature please address this bug.

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-08 13:41 UTC, Torres-ssf requested changes
Changes Required :muscle: 
Hi there @gitnyasha 
Great job on this project, but we still have some changes to work on.

- [ ] The application logic should be separated from the DOM manipulations tasks. [Print](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) of the requirement.

- [ ] There is a bug in your app. The change between Celsius and Fahrenheit does not always happen as expected. Sometimes it works, sometimes it doesn't
![bug](https://user-images.githubusercontent.com/30977845/84036211-4ad49380-a973-11ea-8fa5-71a9058e21f7.gif)

- [ ] As it said in the requirements, the change between Celsius and Fahrenheit should trigger another request in the API with the desired scale.
[Print](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/requests_requirement.png) of the requirement

Please kindly submit for code review again after making these changes.
Happy Coding :computer: 

**Sergio Torres**

2020-06-09 19:19 UTC, bellom requested changes
## Hi @gitnyasha   :clap: 

**For some reason I didn't see your recent changes**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-09 19:19 UTC, bellom commented on src/weather.js
> +    this.city = city;
According to the previous review, @Torres-ssf mentioned calling different `API`

kindly check the screenshot from the pathwright below;
![image](https://user-images.githubusercontent.com/31897434/84189734-a6933f80-aa8d-11ea-8d60-7dc908bbf80a.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622133/

2020-06-09 19:19 UTC, bellom commented on src/index.js
> +}
According to the previous review, @Torres-ssf mentioned that the `toggle button` is not working properly, kindly look into this, still not working.

2020-06-10 17:40 UTC, shloch approved these changes
### Good to go.....you get a thumbs up

![weather](https://user-images.githubusercontent.com/40712459/84300107-c0925800-ab49-11ea-8583-42b698ca04bf.gif)

2020-06-10 17:57 UTC, merged